name: 'auto-release'
on:
  push:
    branches:
      - main
jobs:
  test-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lucernae/container-builder-workflow@main
        id: meta
      - run: |
          echo "${{ toJSON(steps.meta.outputs) }"